spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : greeting-api
          uri: lb://GREETING-API
          predicates:
            - Path=/api/greeting
          filters:
            - JwtAuthenticationFilter
        - id : greeting-security
          uri: lb://GREETING-SECURITY
          predicates:
            - Path=/security/**
  security:
    jwt:
      key: SecretKey-jwt-key-github.com-SoonMyeong
      issuer: test

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
