server:
  port: 8762



eureka:
  instance:
    hostname: eureka2
  #  server:
#    response-cache-update-interval-ms: 1000 # 1?
#    enable-self-preservation: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
spring:
  application:
    name: eureka-sever
