server:
  port: 8081

spring:
  application:
    name: greeting-api

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka1:8761/eureka}, ${EUREKA_URI:http://eureka2:8762/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
